version: '3'

networks:
  your-app-network:
    driver: bridge

services:
  #---------------
  # Postgres DB
  #---------------
  database:
    image: postgis/postgis:15-3.3
    container_name: travelly_database
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata/
      - POSTGRES_HOST=db_postgis_travelly
      - POSTGRES_DB=travelly
      - POSTGRES_PASSWORD=travelly
      - POSTGRES_USER=travelly
    volumes:
      - ./data-db/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      your-app-network:
        aliases:
          - travelly-network

  #---------------
  # Backend
  #---------------
  server:
    container_name: travelly_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - DB_ENGINE=django.contrib.gis.db.backends.postgis
      - DB_HOST=db_postgis_travelly
      - DB_NAME=travelly
      - DB_USER=travelly
      - DB_PASSWORD=travelly
      - DB_PORT=5432
      - DEBUG=true
    depends_on:
      - database
    volumes:
      - .:/code
    tty: true
    stdin_open: true
    networks:
      your-app-network:
        aliases:
          - travelly-network

    command: sh -c "python3 docker/start_server.py"
    ports:
      - "9001:9001"